### ISSUE TITLE
Menu buttons need offset on iPhone XS

### ISSUE THREAD

**Issue by benptc** [ptcrealitylab/vuforia-spatial-toolbox-userinterface#110]
The "notched" screen of iPhone XS covers up part of the sidebar buttons. Make sure they get properly repositioned for each phone model with that screen shape.

**Comment by realityLabDiscourseUser** [comment]
This issue has been mentioned on **Vuforia Spatial Toolbox Community**. There might be relevant details there:

https://forum.spatialtoolbox.vuforia.com/t/app-buttons-get-cut-off/122/2
