### ISSUE TITLE
Logic block menu shows at most 24 blocks

### ISSUE THREAD

**Issue by benptc** [ptcrealitylab/vuforia-spatial-toolbox-userinterface#122]
If you create more blocks than that via add-ons, they don't appear in the menu.

**Comment by realityLabDiscourseUser** [comment]
This issue has been mentioned on **Vuforia Spatial Toolbox Community**. There might be relevant details there:

https://forum.spatialtoolbox.vuforia.com/t/logic-block-options/135/6

**Comment by benptc** [comment]
I found the problem: `menuCols` and `menuRows` are hard-coded to be a 4x6 menu. Cols should stay the same but rows should increase to fit as many blocks as we have.

**Comment by benptc** [comment]
Fixed by PR #123
