### ISSUE TITLE
glcanvas resolution is not responsive

### ISSUE THREAD

**Issue by afustePTC** [ptcrealitylab/vuforia-spatial-toolbox-userinterface#143]
In index.html, the resolution of the canvas is hard set to 736x414. This causes the interface to look wrong in some devices.

`<canvas id="glcanvas" width="736" height="414" 
        style="position: absolute; left: 0; top: 0; width: 736px; height: 414px; background: transparent; 
        pointer-events: none;">
</canvas>`

**Comment by benptc** [comment]
Thanks for reporting this!

**Comment by benptc** [comment]
Fixed in PR #145
