### ISSUE TITLE
Experiment: Alternative motionStudy csv export: chunk-by-chunk

### ISSUE THREAD

**Issue by hobinjk-ptc** [ptcrealitylab/vuforia-spatial-toolbox-userinterface#605]
May provide useful data for fine-grained analysis in other tools

**Comment by ptc-mklaudiny** [comment]
More lightweight thing to do first and give them bit more precise information -  exporting number of samples (individual poses) in a given time interval  (we do not reliably record at regular 10 fps) and the sum of metric (in case of REBA, the sum is somewhat closer to their counting for MURI)
