### ISSUE TITLE
Make the "Found Objects" list interactive for anchors

### ISSUE THREAD

**Issue by benptc** [ptcrealitylab/vuforia-spatial-toolbox-userinterface#91]
Allow users to snap anchors to their current screen position by tapping on them in the found objects list in the settings.

**Comment by realityLabDiscourseUser** [comment]
This issue has been mentioned on **Vuforia Spatial Toolbox Community**. There might be relevant details there:

https://forum.spatialtoolbox.vuforia.com/t/area-targets-and-hue-interface/64/16

**Comment by benptc** [comment]
This feature has been added! 👍
