### ISSUE TITLE
Make node size dependent on target size

### ISSUE THREAD

**Issue by afustePTC** [ptcrealitylab/vuforia-spatial-toolbox-userinterface#95]
If I create a target of 0.02 units size (2 cm), the nodes appear very big in my interface and it is hard to interact with them. If I set the same target to be 1 unit size (1 meter), the nodes appear way smaller on my interface as the library thinks I am further away from the target.
The node size should depend on target size so that it adapts to different scales.

**Comment by benptc** [comment]
As of PR #140 the nodes should be all rendered with the correct size (roughly the size of a coin) assuming the target size was set to an accurate meter-scale measurement.
